name: Deploy Component Docs to GCloud Bucket
on:
    push:
        branches:
            - feature/deploy-to-gcloud-bucket
jobs:
    build:
        name: Build & Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: refs/heads/main
                  fetch-depth: 1
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
            - run: npm run docs.build
            - name: Authenticate on Google Cloud Storage
              uses: google-github-actions/auth@v0
              with:
                  service_account: ${{ secrets.GCP_SA_EMAIL }}
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
            - run: gsutil -m rsync -d -c -r docs gs://mi-components-docs
            - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://mi-components-docs/**/*.html
            - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://mi-components-docs/**/*.js
            - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://mi-components-docs/**/*.css
