name: "Components: Deploy Docs to GCloud Bucket"

# This workflow is dependent on a successful run of the other workflow to bump version and releasing to npm
on:
  workflow_run:
    workflows: ["Components: Bump version and release to npm"]

jobs:
  build_deploy_components_docs:
    name: "Build & Deploy Components Docs"
    runs-on: ubuntu-latest
    # Check out the repository code, but only the latest version.
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/main
          fetch-depth: 1
      # Set up a node environment in the container.
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      # It is absolutely essential to use "CI=" as the first part of the lerna command, or it won't build properly.
      - run: |
          CI= npx lerna run build
          cd packages/components
          npm run build
          npm run docs.build
      - name: "Authenticate on Google Cloud Storage"
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      # This command uses gsutil CLI to sync the local folder with the one on the bucket.
      # "-m" ensures parallel upload of files, "-d" mirrors the folders, "-c" compares checksums to avoid unnecessary uploads, "-r" is for a recursive sync into all folders.
      - run: gsutil -m rsync -d -c -r packages/components/docs gs://mi-components-documentation
      # This is to control cache and set it as low as possible so new changes are instantly available.
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=0"
          gs://mi-components-documentation/**/*.html
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=0"
          gs://mi-components-documentation/**/*.js
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=0"
          gs://mi-components-documentation/**/*.css
