name: Deploy Component Docs to GCloud Bucket
on:
    push:
        branches:
            - feature/*
        paths:
            - packages/components/**
jobs:
    build-deploy-components-docs:
        name: Build & Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: refs/heads/main
                  fetch-depth: 1
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Authenticate on Google Cloud Storage
              uses: google-github-actions/auth@v1
              with:
                  service_account: ${{ secrets.GCP_SA_EMAIL }}
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"
              with:
                  version: ">= 416.0.0"
            - run: gsutil -m rsync -d -c -r test.md gs://mi-components-docs
            - run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600"
                  gs://mi-components-docs/**/*.html
            - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000"
                  gs://mi-components-docs/**/*.js
            - run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000"
                  gs://mi-components-docs/**/*.css
